# Generated by Django 2.2.2 on 2019-06-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=30)),
                ('trip_complete', models.BooleanField(default=False)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('cost_per_ton', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('expenses', models.BigIntegerField(blank=True, null=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='truck.Truck')),
            ],
        ),
    ]
