# Generated by Django 2.2.2 on 2019-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_start_date', models.DateField(blank=True, null=True)),
                ('trip_end_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_complete', models.BooleanField(default=False)),
                ('total_weight', models.FloatField(blank=True, null=True)),
                ('rec_weight', models.FloatField(blank=True, null=True)),
                ('cost_per_ton', models.FloatField(blank=True, null=True)),
                ('shortage', models.FloatField(blank=True, null=True)),
                ('less', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('mop', models.CharField(blank=True, max_length=30)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('tp_pass', models.CharField(blank=True, max_length=100)),
                ('advance', models.FloatField(blank=True, default=0.0, null=True)),
                ('sl_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('truck', 'trip_start_date', 'sl_no')},
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('expense', models.FloatField(blank=True, default=0.0, null=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('truck', 'expense_date', 'comment', 'expense')},
            },
        ),
    ]
