# Generated by Django 2.2.2 on 2019-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='consignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='item',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
