# Generated by Django 2.2.2 on 2019-06-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='start_time',
            new_name='trip_end_time',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_date',
            new_name='trip_start_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost_per_ton',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
