# Generated by Django 2.2.2 on 2019-06-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_auto_20190625_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='consignee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost_per_ton',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
