# Generated by Django 2.2.2 on 2019-07-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_auto_20190724_2241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('trip_start_date', 'trip_start_time', 'consignee', 'driver')},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='truck',
        ),
    ]
