# Generated by Django 2.2.2 on 2019-07-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_auto_20190724_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('truck', 'trip_start_date', 'trip_start_time', 'consignee', 'driver')},
        ),
    ]
