# Generated by Django 2.2.2 on 2019-06-26 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_auto_20190625_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='expense',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck', to='truck.Truck'),
        ),
    ]
