# Generated by Django 2.2.2 on 2019-06-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_auto_20190626_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='comment',
            field=models.TextField(blank=True, default='Trip Started:', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='expense',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
