# Generated by Django 2.2.2 on 2019-07-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0005_auto_20190724_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='diesel',
        ),
    ]
