# Generated by Django 2.2.2 on 2019-06-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0006_auto_20190630_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
