# Generated by Django 2.2.2 on 2019-06-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0008_auto_20190630_1419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('truck', 'trip_start_date', 'trip_start_time', 'consignee', 'driver')},
        ),
    ]
