# Generated by Django 2.2.2 on 2019-07-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0009_auto_20190630_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='expense',
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('expense', models.FloatField(blank=True, default=0.0, null=True)),
                ('expense_date', models.TimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('truck', 'expense_date', 'comment', 'expense')},
            },
        ),
    ]
