# Generated by Django 2.1.8 on 2019-07-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0010_auto_20190701_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
